import type { IPLData } from "./types"

export const dummyData: IPLData = {
  lastUpdated: new Date().toISOString(),
  liveMatch: {
    id: "match1",
    team1: {
      id: "csk",
      name: "Chennai Super Kings",
      shortName: "CSK",
      score: "120/3 (15.2)",
    },
    team2: {
      id: "mi",
      name: "Mumbai Indians",
      shortName: "MI",
      score: "Yet to bat",
    },
    date: new Date().toISOString(),
    venue: "M.A. Chidambaram Stadium, Chennai",
    matchNumber: "Match 23",
    matchType: "League",
    status: "live",
    status_text: "CSK are batting first",
    currentOver: "15.2",
    matchProgress: 75,
  },
  upcomingMatches: [
    {
      id: "match2",
      team1: {
        id: "rcb",
        name: "Royal Challengers Bangalore",
        shortName: "RCB",
      },
      team2: {
        id: "rr",
        name: "Rajasthan Royals",
        shortName: "RR",
      },
      date: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
      venue: "M. Chinnaswamy Stadium, Bangalore",
      matchNumber: "Match 24",
      matchType: "League",
      status: "upcoming",
    },
    {
      id: "match3",
      team1: {
        id: "dc",
        name: "Delhi Capitals",
        shortName: "DC",
      },
      team2: {
        id: "kkr",
        name: "Kolkata Knight Riders",
        shortName: "KKR",
      },
      date: new Date(Date.now() + 172800000).toISOString(), // Day after tomorrow
      venue: "Arun Jaitley Stadium, Delhi",
      matchNumber: "Match 25",
      matchType: "League",
      status: "upcoming",
    },
  ],
  pointsTable: [
    {
      id: "kkr",
      name: "Kolkata Knight Riders",
      shortName: "KKR",
      played: 6,
      won: 5,
      lost: 1,
      noResult: 0,
      points: 10,
      netRunRate: 1.538,
      positionDiff: 0,
      form: ["W", "W", "W", "L", "W"],
    },
    {
      id: "rr",
      name: "Rajasthan Royals",
      shortName: "RR",
      played: 6,
      won: 5,
      lost: 1,
      noResult: 0,
      points: 10,
      netRunRate: 0.767,
      positionDiff: 1,
      form: ["W", "W", "L", "W", "W"],
    },
    {
      id: "csk",
      name: "Chennai Super Kings",
      shortName: "CSK",
      played: 6,
      won: 4,
      lost: 2,
      noResult: 0,
      points: 8,
      netRunRate: 0.726,
      positionDiff: -1,
      form: ["W", "L", "W", "W", "L"],
    },
    {
      id: "lsg",
      name: "Lucknow Super Giants",
      shortName: "LSG",
      played: 6,
      won: 3,
      lost: 3,
      noResult: 0,
      points: 6,
      netRunRate: 0.038,
      positionDiff: 0,
      form: ["W", "L", "W", "L", "L"],
    },
    {
      id: "srh",
      name: "Sunrisers Hyderabad",
      shortName: "SRH",
      played: 6,
      won: 3,
      lost: 3,
      noResult: 0,
      points: 6,
      netRunRate: -0.102,
      positionDiff: 2,
      form: ["L", "W", "L", "W", "L"],
    },
    {
      id: "dc",
      name: "Delhi Capitals",
      shortName: "DC",
      played: 7,
      won: 3,
      lost: 4,
      noResult: 0,
      points: 6,
      netRunRate: -0.187,
      positionDiff: -1,
      form: ["L", "W", "L", "W", "L"],
    },
    {
      id: "gt",
      name: "Gujarat Titans",
      shortName: "GT",
      played: 7,
      won: 3,
      lost: 4,
      noResult: 0,
      points: 6,
      netRunRate: -0.479,
      positionDiff: -1,
      form: ["L", "W", "L", "L", "W"],
    },
    {
      id: "rcb",
      name: "Royal Challengers Bangalore",
      shortName: "RCB",
      played: 7,
      won: 3,
      lost: 4,
      noResult: 0,
      points: 6,
      netRunRate: -0.738,
      positionDiff: 0,
      form: ["L", "W", "L", "W", "L"],
    },
    {
      id: "pbks",
      name: "Punjab Kings",
      shortName: "PBKS",
      played: 7,
      won: 2,
      lost: 5,
      noResult: 0,
      points: 4,
      netRunRate: -0.251,
      positionDiff: 0,
      form: ["L", "L", "W", "L", "L"],
    },
    {
      id: "mi",
      name: "Mumbai Indians",
      shortName: "MI",
      played: 6,
      won: 1,
      lost: 5,
      noResult: 0,
      points: 2,
      netRunRate: -1.044,
      positionDiff: 0,
      form: ["L", "L", "L", "W", "L"],
    },
  ],
  schedule: [
    {
      id: "match1",
      team1: {
        id: "csk",
        name: "Chennai Super Kings",
        shortName: "CSK",
      },
      team2: {
        id: "mi",
        name: "Mumbai Indians",
        shortName: "MI",
      },
      date: new Date().toISOString(),
      venue: "M.A. Chidambaram Stadium, Chennai",
      matchNumber: "Match 23",
      matchType: "League",
      status: "completed",
      result: "CSK won by 20 runs",
    },
    {
      id: "match2",
      team1: {
        id: "rcb",
        name: "Royal Challengers Bangalore",
        shortName: "RCB",
      },
      team2: {
        id: "rr",
        name: "Rajasthan Royals",
        shortName: "RR",
      },
      date: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
      venue: "M. Chinnaswamy Stadium, Bangalore",
      matchNumber: "Match 24",
      matchType: "League",
      status: "upcoming",
    },
    {
      id: "match3",
      team1: {
        id: "dc",
        name: "Delhi Capitals",
        shortName: "DC",
      },
      team2: {
        id: "kkr",
        name: "Kolkata Knight Riders",
        shortName: "KKR",
      },
      date: new Date(Date.now() + 172800000).toISOString(), // Day after tomorrow
      venue: "Arun Jaitley Stadium, Delhi",
      matchNumber: "Match 25",
      matchType: "League",
      status: "upcoming",
    },
    {
      id: "match4",
      team1: {
        id: "gt",
        name: "Gujarat Titans",
        shortName: "GT",
      },
      team2: {
        id: "pbks",
        name: "Punjab Kings",
        shortName: "PBKS",
      },
      date: new Date(Date.now() + 259200000).toISOString(), // 3 days from now
      venue: "Narendra Modi Stadium, Ahmedabad",
      matchNumber: "Match 26",
      matchType: "League",
      status: "upcoming",
    },
    {
      id: "match5",
      team1: {
        id: "srh",
        name: "Sunrisers Hyderabad",
        shortName: "SRH",
      },
      team2: {
        id: "lsg",
        name: "Lucknow Super Giants",
        shortName: "LSG",
      },
      date: new Date(Date.now() + 345600000).toISOString(), // 4 days from now
      venue: "Rajiv Gandhi International Stadium, Hyderabad",
      matchNumber: "Match 27",
      matchType: "League",
      status: "upcoming",
    },
    {
      id: "match6",
      team1: {
        id: "mi",
        name: "Mumbai Indians",
        shortName: "MI",
      },
      team2: {
        id: "csk",
        name: "Chennai Super Kings",
        shortName: "CSK",
      },
      date: new Date(Date.now() + 432000000).toISOString(), // 5 days from now
      venue: "Wankhede Stadium, Mumbai",
      matchNumber: "Match 28",
      matchType: "League",
      status: "upcoming",
    },
  ],
}

